import { Archive, ArrowLeft, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, FileText, Loader2, Pencil, Plus, RotateCcw, Search, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import PublicHeader from "@/components/PublicHeader";
import SeoMeta from "@/components/SeoMeta";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatTHB } from "@/lib/document";
import { trpc } from "@/lib/trpc";
import "../styles/customer-master.css";

type Customer = { id: number; customerType: "company" | "person"; name: string; taxId: string | null; address: string | null; contactName: string | null; phone: string | null; email: string | null; note: string | null; archivedAt: Date | string | null; documentCount: number; receivableCount: number; outstandingAmount: string };
type CustomerForm = { customerType: "company" | "person"; name: string; taxId: string; address: string; contactName: string; phone: string; email: string; note: string };
const blankForm: CustomerForm = { customerType: "company", name: "", taxId: "", address: "", contactName: "", phone: "", email: "", note: "" };
const toForm = (customer: Customer): CustomerForm => ({ customerType: customer.customerType, name: customer.name, taxId: customer.taxId || "", address: customer.address || "", contactName: customer.contactName || "", phone: customer.phone || "", email: customer.email || "", note: customer.note || "" });

export default function CustomersPage() {
  const { isAuthenticated, loading } = useAuth();
  const utils = trpc.useUtils();
  const [query, setQuery] = useState("");
  const [debouncedQuery, setDebouncedQuery] = useState("");
  const [archived, setArchived] = useState(false);
  const [page, setPage] = useState(1);
  const [editing, setEditing] = useState<Customer | null>(null);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [form, setForm] = useState<CustomerForm>(blankForm);
  const [feedback, setFeedback] = useState("");
  const [duplicateMatches, setDuplicateMatches] = useState<Array<Pick<Customer, "id" | "name" | "taxId" | "archivedAt">>>([]);
  useEffect(() => { const timer = window.setTimeout(() => { setDebouncedQuery(query.trim()); setPage(1); }, 250); return () => window.clearTimeout(timer); }, [query]);
  const listInput = useMemo(() => ({ query: debouncedQuery || undefined, archived, page, pageSize: 10 }), [archived, debouncedQuery, page]);
  const customersQuery = trpc.customers.list.useQuery(listInput, { enabled: isAuthenticated });
  const refresh = async () => { await utils.customers.list.invalidate(); };
  const closeDialog = () => { setEditing(null); setIsCreateOpen(false); setForm(blankForm); setDuplicateMatches([]); setFeedback(""); };
  const openEdit = (customer: Customer) => { setEditing(customer); setForm(toForm(customer)); setDuplicateMatches([]); setFeedback(""); };
  const create = trpc.customers.create.useMutation({ onSuccess: async (result) => { setDuplicateMatches(result.duplicateMatches); if (!result.duplicateMatches.length) { setFeedback(`เพิ่มลูกค้า “${result.customer.name}” แล้ว`); await refresh(); closeDialog(); } }, onError: (error) => setFeedback(error.message || "ไม่สามารถเพิ่มลูกค้าได้") });
  const update = trpc.customers.update.useMutation({ onSuccess: async (result) => { setDuplicateMatches(result.duplicateMatches); if (!result.duplicateMatches.length) { setFeedback(`บันทึกข้อมูล “${result.customer.name}” แล้ว`); await refresh(); closeDialog(); } }, onError: (error) => setFeedback(error.message || "ไม่สามารถบันทึกข้อมูลลูกค้าได้") });
  const archive = trpc.customers.setArchived.useMutation({ onSuccess: async (customer) => { setFeedback(customer.archivedAt ? `เก็บ “${customer.name}” ไว้ในรายการเก็บถาวรแล้ว` : `กู้คืน “${customer.name}” แล้ว`); await refresh(); }, onError: (error) => setFeedback(error.message || "ไม่สามารถเปลี่ยนสถานะลูกค้าได้") });
  const submit = () => { setFeedback(""); if (editing) update.mutate({ id: editing.id, customer: form }); else create.mutate(form); };
  const totalPages = Math.max(1, Math.ceil((customersQuery.data?.total || 0) / (customersQuery.data?.pageSize || 10)));
  const isPending = create.isPending || update.isPending;

  if (loading) return <div className="customers-loading"><Loader2 className="animate-spin" /> กำลังตรวจสอบบัญชีผู้ใช้</div>;
  if (!isAuthenticated) return <><PublicHeader /><main className="customers-guest"><UsersRound size={36} /><h1>รายชื่อลูกค้าของคุณ</h1><p>เข้าสู่ระบบเพื่อเก็บข้อมูลลูกค้า เลือกใช้ในเอกสาร และติดตามยอดที่สัมพันธ์กัน</p></main></>;
  const items = customersQuery.data?.items || [];
  return <div className="app-page customers-page"><SeoMeta title="รายชื่อลูกค้า | Tools Thai" description="จัดเก็บและนำข้อมูลลูกค้าไปใช้กับเอกสารธุรกิจของคุณ" canonicalPath="/customers" /><PublicHeader /><main className="customers-workspace"><div className="shell"><header className="customers-hero"><div><Link href="/tools" className="back-link"><ArrowLeft size={16} /> เครื่องมือทั้งหมด</Link><p className="page-kicker">CUSTOMER MASTER</p><h1>รายชื่อลูกค้า</h1><p>เก็บข้อมูลลูกค้าไว้ใช้ซ้ำในเอกสาร โดยคุณยังแก้เฉพาะเอกสารแต่ละฉบับได้ตามต้องการ</p></div><button type="button" className="button button-download" onClick={() => { setIsCreateOpen(true); setForm(blankForm); }}><Plus size={17} /> เพิ่มลูกค้า</button></header>
    <section className="customers-controls" aria-label="ค้นหาและกรองลูกค้า"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาชื่อ เลขภาษี หรือผู้ติดต่อ" aria-label="ค้นหารายชื่อลูกค้า" /></label><button type="button" className={archived ? "customers-archive-toggle is-active" : "customers-archive-toggle"} onClick={() => { setArchived((value) => !value); setPage(1); }}>{archived ? <RotateCcw size={16} /> : <Archive size={16} />}{archived ? "กำลังดูรายการเก็บถาวร" : "ดูรายการเก็บถาวร"}</button></section>
    {feedback ? <p className="customers-feedback" role="status">{feedback}</p> : null}
    <section className="customers-card" aria-live="polite">{customersQuery.isLoading ? <div className="customers-state"><Loader2 className="animate-spin" /><strong>กำลังโหลดรายชื่อลูกค้า</strong></div> : customersQuery.isError ? <div className="customers-state"><CircleAlert /><strong>ไม่สามารถโหลดรายชื่อลูกค้าได้</strong><button type="button" onClick={() => void customersQuery.refetch()}>ลองใหม่</button></div> : !items.length ? <div className="customers-state"><UsersRound size={28} /><strong>{archived ? "ยังไม่มีลูกค้าที่เก็บถาวร" : query ? "ไม่พบลูกค้าที่ตรงกับคำค้นหา" : "ยังไม่มีรายชื่อลูกค้า"}</strong><span>{archived ? "ลูกค้าที่เก็บถาวรจะแสดงที่นี่และกู้คืนได้ทุกเมื่อ" : "เพิ่มลูกค้าจากหน้านี้ หรือจาก Customer Picker ในเอกสาร"}</span>{!archived && !query ? <button type="button" className="text-icon-button" onClick={() => setIsCreateOpen(true)}><Plus size={15} /> เพิ่มลูกค้ารายแรก</button> : null}</div> : <><div className="customers-table-wrap"><table><thead><tr><th>ลูกค้า</th><th>ติดต่อ</th><th>เอกสาร</th><th>ยอดคงเหลือ</th><th><span className="sr-only">จัดการ</span></th></tr></thead><tbody>{items.map((customer) => <tr key={customer.id}><td><strong>{customer.name}</strong><small>{customer.customerType === "company" ? "บริษัท / นิติบุคคล" : "บุคคล"}{customer.taxId ? ` · ${customer.taxId}` : ""}</small></td><td><span>{customer.contactName || "—"}</span><small>{customer.phone || customer.email || "ยังไม่ระบุ"}</small></td><td><span><FileText size={14} /> {customer.documentCount} เอกสาร</span><small>{customer.receivableCount} รายการลูกหนี้</small></td><td><strong className="customers-outstanding">{formatTHB(Number(customer.outstandingAmount))}</strong></td><td className="customers-actions"><button type="button" onClick={() => openEdit(customer)}><Pencil size={14} /> แก้ไข</button><button type="button" disabled={archive.isPending} onClick={() => archive.mutate({ id: customer.id, archived: !customer.archivedAt })}>{customer.archivedAt ? <RotateCcw size={14} /> : <Archive size={14} />}{customer.archivedAt ? "กู้คืน" : "เก็บ"}</button></td></tr>)}</tbody></table></div>{totalPages > 1 ? <nav className="customers-pagination" aria-label="แบ่งหน้ารายชื่อลูกค้า"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft size={16} /> ก่อนหน้า</button><span>หน้า {page} จาก {totalPages} · {customersQuery.data?.total} รายการ</span><button type="button" disabled={page >= totalPages} onClick={() => setPage((value) => value + 1)}>ถัดไป <ChevronRight size={16} /></button></nav> : null}</>}</section>
    <CustomerDialog open={isCreateOpen || Boolean(editing)} isEdit={Boolean(editing)} form={form} feedback={feedback} duplicateMatches={duplicateMatches} pending={isPending} onFormChange={setForm} onSubmit={submit} onClose={closeDialog} onAcceptDuplicate={async () => { await refresh(); closeDialog(); }} />
  </div></main></div>;
}

function CustomerDialog({ open, isEdit, form, feedback, duplicateMatches, pending, onFormChange, onSubmit, onClose, onAcceptDuplicate }: { open: boolean; isEdit: boolean; form: CustomerForm; feedback: string; duplicateMatches: Array<Pick<Customer, "id" | "name" | "taxId" | "archivedAt">>; pending: boolean; onFormChange: (form: CustomerForm) => void; onSubmit: () => void; onClose: () => void; onAcceptDuplicate: () => Promise<void> }) {
  const set = <K extends keyof CustomerForm>(key: K, value: CustomerForm[K]) => onFormChange({ ...form, [key]: value });
  return <Dialog open={open} onOpenChange={(value) => { if (!value) onClose(); }}><DialogContent className="customer-master-dialog"><DialogHeader><DialogTitle>{isEdit ? "แก้ไขข้อมูลลูกค้า" : "เพิ่มลูกค้าใหม่"}</DialogTitle><DialogDescription>การแก้ไขที่นี่มีผลกับ Customer Master เท่านั้น และจะไม่เขียนทับเอกสารที่สร้างไว้แล้ว</DialogDescription></DialogHeader>{duplicateMatches.length ? <div className="customer-duplicate-warning" role="status"><CircleAlert size={17} /><div><strong>พบชื่อหรือเลขภาษีคล้ายกัน</strong><p>{duplicateMatches.map((customer) => `${customer.name}${customer.taxId ? ` (${customer.taxId})` : ""}${customer.archivedAt ? " — เก็บถาวร" : ""}`).join(" · ")}</p><button type="button" onClick={() => void onAcceptDuplicate()}>ยืนยันเก็บข้อมูลนี้ต่อ</button></div></div> : <div className="customer-master-fields"><label>ประเภทลูกค้า<select value={form.customerType} onChange={(event) => set("customerType", event.target.value as CustomerForm["customerType"])}><option value="company">บริษัท / นิติบุคคล</option><option value="person">บุคคล</option></select></label><label>ชื่อบริษัท / ชื่อลูกค้า<input value={form.name} onChange={(event) => set("name", event.target.value)} maxLength={255} autoFocus /></label><label>เลขประจำตัวผู้เสียภาษี<input value={form.taxId} onChange={(event) => set("taxId", event.target.value.replace(/\D/g, "").slice(0, 13))} inputMode="numeric" placeholder="13 หลัก (หากมี)" /></label><label>ที่อยู่<textarea rows={3} value={form.address} onChange={(event) => set("address", event.target.value)} /></label><div className="customer-master-split"><label>ผู้ติดต่อ<input value={form.contactName} onChange={(event) => set("contactName", event.target.value)} /></label><label>โทรศัพท์<input value={form.phone} onChange={(event) => set("phone", event.target.value)} /></label></div><label>อีเมล<input type="email" value={form.email} onChange={(event) => set("email", event.target.value)} /></label><label>หมายเหตุ<textarea rows={2} value={form.note} onChange={(event) => set("note", event.target.value)} /></label></div>}{feedback && !duplicateMatches.length ? <p className="customer-form-feedback" role="status">{feedback}</p> : null}<DialogFooter>{duplicateMatches.length ? <button type="button" className="workspace-action" onClick={onClose}>ปิด</button> : <><button type="button" className="workspace-action" onClick={onClose}>ยกเลิก</button><button type="button" className="button button-download" disabled={!form.name.trim() || pending} onClick={onSubmit}>{pending ? <Loader2 className="animate-spin" size={16} /> : <CheckCircle2 size={16} />}{isEdit ? "บันทึกการแก้ไข" : "บันทึกลูกค้า"}</button></>}</DialogFooter></DialogContent></Dialog>;
}
